### ISSUE TITLE
Bug: Sometimes the app doesn't close

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailDatasetBrowser#20]
Occasionally, the app doesn't ``dispose`` when using the exit button (the exit cross). It closes the dataset, and does so without any throwing any exceptions, however, it simply does not close the application. If you close the app a second time, it does work properly.

This seems to be replicable when you iterate through the email browse panel quickly (i.e. by holding down the down button for a bit), and then closing the application.

**Comment by andrewlalis** [comment]
I just tried to replicate this by rapidly navigating through a really big lucene result set, and I still can't get it to show this bug. Maybe it's some non-deterministic behavior because of the threaded nature of the progress dialog that appears when closing the dataset? I'm running a ryzen threadripper so I often end up over-estimating the parallelism I can get away with. Maybe see if removing the progress dialog makes any difference.

**Comment by andrewlalis** [comment]
Fixed in v2.12.1 It was an issue with how events were propagated, where your structural change to how the search panels was set up lead to a null pointer exception when the dataset was set to null.
